version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  device-status:
    lang: node12
    handler: ./device-status
    image: 3003611762/device-status:latest
    environment:
      db_port: 5432
      db_name: postgres
    secrets:
      - db

